name: CI/CD Pipeline Production

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Jalankan Proses Build
        run: |
          echo "Memulai proses build di Cloud Runner..."
          mkdir dist
          echo "<h1>Ini adalah hasil build otomatis Artifact</h1>" > dist/index.html
          echo "Build selesai"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-build-web
          path: dist/

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-app

    steps:
      # 1. Download artifact dari stage sebelumnya
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: hasil-build-web
          path: dist/

      # 2. Transfer ke VPS via SCP
      - name: Copy Artifact to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html"

      # 3. Eksekusi perintah di VPS via SSH
      - name: Execute Command via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Memulai proses restart service di VPS..."
            systemctl reload nginx
            echo "Deployment Production Sukses!"